### ISSUE TITLE
Add scheduler for daily query top 10 users by trust points

### ISSUE THREAD

**Issue by Nairda015** [Nairda015/IGroceryStore#44]
Should run for eg. daily.
Maybe cron notation provided by modulesetting.json

**Comment by GrzegorzFedoryka** [comment]
What exactly queueing means in this context?

**Comment by Nairda015** [comment]
There was typo in title

**Comment by GrzegorzFedoryka** [comment]
I get that. But what to do with query result? I mean save it somewhere or push it to rabbit (i have no idea how rabbit works 🐇) or just query it to cache it and make optimalizer easier to reach on?

**Comment by Nairda015** [comment]
Cache sounds great so maybe scheduler isn't necessary?

**Comment by GrzegorzFedoryka** [comment]
Maybe not. It may be reached ex. with index on desc user trust points
